version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    depends_on:
      - kafka
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      # 1) Define all your listeners
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      # 2) Tell Kafka which of those are PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # 3) Which listener(s) to *enable* (must match names above)
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      # 4) How brokers talk to each other
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # 5) What your clients see (DNS names/ports)
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094
      # And your other settings…
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9093:9093"
    networks:
      - kafka_network
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    environment:
      ZK_HOSTS: "zookeeper:2181"
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    networks:
      - kafka_network

  producer:
    build: ./producer
    container_name: demo-producer
    environment:
      - KAFKA_BROKER=kafka:9093
      - KAFKA_TOPIC=demo-topic
      - ENCRYPTION_KEY=mysupersecretkey
    depends_on:
      - kafka
    networks:
      - kafka_network

  consumer:
    build: ./consumer
    container_name: demo-consumer
    environment:
      - KAFKA_BROKER=kafka:9093
      - KAFKA_TOPIC=demo-topic
      - ENCRYPTION_KEY=mysupersecretkey
    depends_on:
      - kafka
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

volumes:
  kafka-data: